#pragma config(Sensor, S1,     col1,    sensorEV3_Color)
#pragma config(Sensor, S2,     gyro,    sensorEV3_Gyro)
#pragma config(Sensor, S3,     col2,    sensorEV3_Color)
#pragma config(Sensor, S4,     usonic,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          claw,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheelR,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelL,  tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          hand,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// color1 - LineFollower-is Sensor-i
// color2 - ColorCheck-is Sensor-i

//float lineCorrectionTime = 1000;

float AAAA;
float AAAAAA;

//int cBlack = 8;
//int cDarkBlue = 11;
//int cBlue = 15;
//int cWhite = 76;

float checkedColor = -1;
bool checkStatus = false;

float wheelRadius = 27.4;
float disBetweenWheels = 104;

float sampleTime_receiveData = 10;
float sampleTime_encoderSpeed = 10;

float gyro_angle = 0;
float encoder_WR = 0;
float encoder_WL = 0;
float reflected_col1 = 0;
float reflected_col2 = 0;


float prevEncoderWl = 0;
float prevEncoderWr = 0;
float currEncoderWl = 0;
float currEncoderWr = 0;

float speed_Wl = 0;
float speed_Wr = 0;
float encoredical_angle = 0;
float yaw_angularSpeed = 0;
float prev_yaw_angularSpeed = 0;

float gyro_prev_mes = 0;
float gyro_prev_filtered = 0;
float gyro_curr_mes = 0;
float gyro_curr_filtered = 0;

float encoder_prev_filtered = 0;
float encoder_curr_mes = 0;
float encoder_curr_filtered = 0;

float prev_fusal_velocity = 0;
float curr_fusal_velocity = 0;

float prev_gyroic_velocity = 0;
float gyroic_angle = 0;

float fusal_angle = 0;

#include "AlgorithmTypeFunctions.c"
#include "PID.c"

PID Encoder_move[5];
PID Gyro_Rotate[5];

#include "PID_Usage.c"
#include "PID_tasks.c"
#include "PID_Start.c"
#include "PID_LineFollower.c"
#include "PID_Gyro.c"
#include "PID_Encoder.c"
#include "PID_Functions.c"
#include "PID_Advanced.c"
#include "Tasks.c"
#include "Initialization.c"

task main()
{
	initializate();

	//Encoder_moveMm_Advanced(500);

	//Encoder_move[4].oneSided = true;

	PID_Gyro_Rotate(Gyro_Rotate[1], 180);

	//Encoder_moveMm(Encoder_move[4], 3000);

	//wait(3000);
}
